//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalStoreWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int PurchaseId { get; set; }
        public int Id { get; set; }
        public string MedicineName { get; set; }
        public string MedicineCompanyName { get; set; }
        public int MedicinePrice { get; set; }
        public int MedicineQuantity { get; set; }
        public System.DateTime Date { get; set; }
        public int Amount { get; set; }
    }
}
